version: "3.8"

services:
  # Frontend Next.js Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      # Client-side API URL - browser sẽ gọi qua localhost:5000
      - NEXT_PUBLIC_API_URL_BROWSER=http://localhost:5000/api
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}

      # Application Environment
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Uploads directory (if needed for file sharing with backend)
      - uploads_data:/app/uploads
    networks:
      - shared-network # Connect to backend's network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
          "||",
          "exit",
          "1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  # Use the same network as backend
  shared-network:
    external: true

volumes:
  uploads_data:
    driver: local
